import Head from "next/head";
import { APIKEY } from "../config";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import axios from "axios";

export default function SearchResults() {
	const [data, setData] = useState("");
	const [search, setSearch] = useState("");

	let url = "http://www.omdbapi.com/?i=tt3896198&apikey=2ab6220a";
	const fetchMovieData = async () => {
		try {
			const { data } = await axios.get(url);
			console.log(data);
			setData(JSON.stringify(data));
		} catch (error) {
			console.log(error);
			setData(error);
		}
	};

	useEffect(() => {
		fetchMovieData();
	}, []);

	let listen = "https://music.youtube.com/watch?v=oiKj0Z_Xnjc&feature=share";
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className={`m-2 p-2 ${styles.background}`}>
					<span>MyTestApp</span>
					<h3>Watch something incredible</h3>
				</div>
				<h1>App home</h1>
				<input
					type="text"
					className=""
					value={search}
					onChange={(e) => setSearch(e.target.value)}
				/>
				<p>{data}</p>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}
