import React, { useState, useEffect } from "react";
import { apiKey } from "../config";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import axios from "axios";

const API_URL = "http://www.omdbapi.com/";

export default function SearchResults() {
	const [movies, setMovies] = useState([]);
	const [error, setError] = useState(null);
	const [isLoading, setIsLoading] = useState(false);
	const [searchTerm, setSearchTerm] = useState("");

	async function fetchData(searchTerm) {
		setIsLoading(true);

		try {
			const response = await fetch(
				`${API_URL}?apikey=2ab6220a&s=${searchTerm}`
			);
			const data = await response.json();
			setMovies(data.Search);
		} catch (error) {
			setError(error);
		}

		setIsLoading(false);
	}
	useEffect(() => {
		fetchData();
	}, []);

	const handleSubmit = (event) => {
		event.preventDefault();
		console.log("clicked");
		fetchData(searchTerm);
	};

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={`${styles.background}`}>
				<span>MyTestApp</span>
				<h3>Watch something incredible</h3>
			</div>
			<form onSubmit={handleSubmit} className={`${styles.search}`}>
				<input
					type="text"
					value={searchTerm}
					onChange={(event) => setSearchTerm(event.target.value)}
				/>
				<button type="submit">Search</button>
			</form>
			{/* <span>{movies}</span> */}
			<ul>
				{movies.map((movie) => (
					<li key={movie.imdbID}>{movie.Title}</li>
				))}
			</ul>
		</div>
	);

	if (error) {
		return <p>There was an error loading the movies</p>;
	}
}
